nohup: ignoring input
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/pace/Poseidon/train_multi_gpu.py", line 154, in <module>
    main()
  File "/home/pace/Poseidon/train_multi_gpu.py", line 69, in main
    wandb.init(
    ^^^^^
NameError: name 'wandb' is not defined
Traceback (most recent call last):
  File "/home/pace/Poseidon/train_multi_gpu.py", line 154, in <module>
    main()
  File "/home/pace/Poseidon/train_multi_gpu.py", line 77, in main
    phase = TRAIN_PHASE
            ^^^^^^^^^^^
NameError: name 'TRAIN_PHASE' is not defined
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10393) of binary: /home/pace/anaconda3/envs/poseidon/bin/python
Traceback (most recent call last):
  File "/home/pace/anaconda3/envs/poseidon/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/anaconda3/envs/poseidon/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/pace/anaconda3/envs/poseidon/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/pace/anaconda3/envs/poseidon/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/pace/anaconda3/envs/poseidon/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/anaconda3/envs/poseidon/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_multi_gpu.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-26_12:30:20
  host      : standard-Super-Server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 10394)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-26_12:30:20
  host      : standard-Super-Server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10393)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
